Tweak how we calculate reading time on articles
wellcomecollection/wellcomecollection.org pull request #9781
Opened 2023-05-16 12:35 UTC by alexwlchan

* Include quotes in the reading time calculate
* Round up the number of minutes, rather than to the nearest integer
* Move the code out into a separate file; add proper types

2023-05-16 17:10 UTC, davidpmccormick approved these changes

2023-05-17 09:30 UTC, rcantin-w commented on content/webapp/services/prismic/transformers/articles.ts
> +import { calculateReadingTime, showReadingTime } from 'utils/reading-time';
```suggestion
import { calculateReadingTime, showReadingTime } from '@weco/content/utils/reading-time';
```

2023-05-17 09:35 UTC, rcantin-w requested changes
The suggested code change should fix the test

2023-05-17 09:49 UTC, rcantin-w commented on content/webapp/utils/reading-time.ts
> +  return `${minutes} minute${minutes > 1 ? 's' : ''}`;
We have a `pluralize` function that could help with this in `@weco/common/utils/grammar`

2023-05-17 10:16 UTC, rcantin-w approved these changes

2023-05-17 12:03 UTC, merged